version: '3.9'

services:

  documentations:
    image: squidfunk/mkdocs-material
    working_dir: '/documentations/'
    env_file:
      - .env
    volumes:
      - .:/documentations
    ports:
      - '${DOC_PORT:-9090}:8000'
    container_name: pronochain_documentation
